services:
  postgres:
    image: postgres:16
    container_name: image_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: bookshelf
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  postgres_data: